# create new user and add authorized key to log in
- name: create new group `{{ deploy_group }}`
  group:
    name: "{{ deploy_group }}"
    state: present
  become: true

- name: create non-root user `{{ deploy_user }}` and add it on the group `{{ deploy_group }}
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    shell: "/bin/bash"
  become: true

- name: add authorized_key to non-root user
  authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', authorized_key_filename) }}"
  become: true
